services:
  couchserver:
    image: couchdb:latest
    restart: unless-stopped
    #deploy:
    #  mode: replicated
    #  replicas: 3
    networks:
      - default
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.couchserver.entrypoints=websecure"
      - "traefik.http.routers.couchserver.tls=true"
      - "traefik.http.routers.couchserver.tls.certresolver=myresolver"
      - "traefik.http.routers.couchserver.rule=Host(`HOST`)"

      - "traefik.http.services.couchserver.loadbalancer.server.port=5984"

      - "traefik.docker.network=obsidian-sync_default"
    env_file:
      - .env
    volumes:
      - ./data:/opt/couchdb/data
      - ./etc:/opt/couchdb/etc/local.d

volumes:
  data: {}

networks:
  default:
    driver: bridge
    attachable: true
